#! /bin/sh
#
# Example panel for lemonbar

. panel_colors

SYS_PAD="  "
WS_PAD=" "
num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
    # sysinfo output
		B*)
            BATTERY=${line#?}
            BATTERY=${BATTERY%"%"}
            BAT_ICON=""
            FG_COLOR=$COLOR_DEFAULT_BG
            BG_COLOR=$COLOR_DEFAULT_BG
            if [[ $BATTERY == \+* ]]; then
                BG_COLOR=$BAT_CHARGING
                U_COLOR=$BAT_CHARGING
                BATTERY=${BATTERY#?}
            elif [[ $BATTERY -ge 90 ]]; then
                BG_COLOR=$BAT_NORMAL
                U_COLOR=$BAT_NORMAL
                BAT_ICON=""
            elif [[ $BATTERY -ge 70 ]]; then
                BG_COLOR=$BAT_NORMAL
                U_COLOR=$BAT_NORMAL
                BAT_ICON=""
            elif [[ $BATTERY -ge 20 ]]; then
                BG_COLOR=$BAT_NORMAL
                U_COLOR=$BAT_NORMAL
                BAT_ICON=""
            else
                BG_COLOR=$BAT_CRITICAL
                FG_COLOR=$COLOR_DEFAULT_BG
                U_COLOR=$BAT_CRITICAL
                BAT_ICON=""
            fi
            bat_time=$(acpi -b | awk -F',[ ]*' '{ print $3 }' | sed 's/:/\\\\:/g')
            bat="%{F$FG_COLOR}%{B$BG_COLOR}%{U$U_COLOR}%{A:notify-send "remaining" "$(acpi -b | awk -F',[ ]*' '{ print $3 }' | sed 's/:/\\\\:/g' | cut -d ' ' -f 1)" -t 1000:}$SYS_PAD$BAT_ICON $BATTERY%$SYS_PAD%{A}%{U-}%{B-}%{F-}"
            ;;
        V*)
            VOLUME=${line#?}
            VOL_ICON=""
            FG_COLOR=$COLOR_DEFAULT_BG
            #BG_COLOR=$COLOR_DEFAULT_BG
            BG_COLOR=$VOL_UNMUTE
            U_COLOR=$VOL_UNMUTE
            if [[ $VOLUME == M*  ]]; then
                FG_COLOR=$VOL_MUTE_FG
                BG_COLOR=$VOL_MUTE
                U_COLOR=$VOL_MUTE
                VOLUME=${VOLUME#?}

            fi
            vol="%{F$FG_COLOR}%{B$BG_COLOR}%{U$U_COLOR}%{A3:amixer -D pulse set Master Playback Switch toggle:}$SYS_PAD$VOL_ICON $VOLUME$SYS_PAD%{A}%{U-}%{B-}%{F-}"
            ;;
        N*)
            FG_COLOR=$COLOR_DEFAULT_BG
            BG_COLOR=$COLOR_DEFAULT_BG
            U_COLOR=$NET_U
            BG_COLOR=$NET_BG
            NET_ICON=""
            net="%{F$FG_COLOR}%{B$BG_COLOR}%{U$U_COLOR}$SYS_PAD$NET_ICON ${line#?}$SYS_PAD%{U-}%{B-}%{F-}"
            ;;
        C*)
            FG_COLOR=$COLOR_DEFAULT_FG
            BG_COLOR=$COLOR_DEFAULT_BG
            U_COLOR=$TIME_U
            #BG_COLOR=$TIME_BG
            #CLOCK_ICON=""
            clock="%{F$FG_COLOR}%{B$BG_COLOR}%{U$TIME_U}${line#?}%{U-}%{B-}%{F-}"
            ;;
		T*)
			# xtitle output
      TITLE=$(echo ${line#?} | awk 'BEGIN{FS="[ ]*-[ ]*"; OFS=" - "} { for (i=NF; i>0; i--) { printf "%s", $i;if (i>1) { printf "%s", OFS; }}}' | awk -v len=60 '{if (length($0) > len) print substr($0, 1, len-3) "..."; else print;}')
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}%{U$COLOR_TITLE_U} $TITLE %{U-}%{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wmstate=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
                icon="◯"
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wmstate="${wmstate}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
                icon="◎"
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
                icon="◉"
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						wmstate="${wmstate}%{F${FG}}%{B${COLOR_SYS_BG}}%{A:bspc desktop -f ${name}:}$WS_PAD${icon}$WS_PAD%{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						;;
				esac
				shift
			done
            # Extra paddding to the left to align with gaps
            wmstate="${wmstate}"
			;;
	esac
	printf "%s\n" "%{l}${wmstate}${title}%{c}${clock}%{r}%{+u}${net}${vol}${bat}%{-u}"
done
