#! /bin/sh

sxhkd &

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then
    DIR="$PWD"
fi

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config leaf_monocle         true
bspc config focus_by_distance    true
bspc config history_aware_focus  false

bspc monitor -d main web code media wine chat #add more here

bspc desktop ^2 --layout monocle
bspc desktop ^4 --layout monocle

bspc rule -a Gimp               desktop=^8 state=floating follow=on
bspc rule -a Firefox            desktop=^2
bspc rule -a qutebrowser        desktop=^2
bspc rule -a *:mpv-youtube      desktop=^2
bspc rule -a *:libreoffice      desktop=^4
bspc rule -a Zathura            desktop=^4
bspc rule -a mpv                desktop=^4 follow=on
bspc rule -a NetBeans\ IDE\ 8.1 desktop=^3
bspc rule -a VirtualBox         desktop=^3

bspc config normal_border_color         "#332d29"
bspc config active_border_color         "#DED0BD"
bspc config focused_border_color        "#D1D1D1"
bspc config presel_border_color         "#9a875f"
bspc config urgent_border_color         "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1

bspc config external_rules_command $(which external_rules)

panel &
