#! /bin/sh

BSPWM_STATE=/tmp/bspwm-state.json
export BSPWM_STATE

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

sxhkd &

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then
    DIR="$PWD"
fi

bspc config border_width         1
bspc config window_gap           0
bspc config top_padding         30

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config click_to_focus       true

bspc monitor -d main web code media wine chat #add more here

bspc desktop ^2 --layout monocle
bspc desktop ^4 --layout monocle

bspc rule -a Icecat             desktop='^2'
bspc rule -a google-chrome      desktop='^2'
bspc rule -a qutebrowser        desktop='^2'
bspc rule -a *:mpv-youtube      desktop='^2'
bspc rule -a VirtualBox         desktop='^3'
bspc rule -a NetBeans\ IDE\ 8.2 desktop='^3'
bspc rule -a Emacs              desktop='^3' state=tiled
bspc rule -a Gimp               desktop='^4' state=floating follow=on
bspc rule -a *:libreoffice      desktop='^4' state=tiled
bspc rule -a Zathura            desktop='^4' state=tiled follow=on
bspc rule -a mpv                desktop='^4' follow=on

bspc config normal_border_color         "#4F4A46"
bspc config active_border_color         "#4C5754"
bspc config focused_border_color        "#A0BAB3"
bspc config presel_border_color         "#9a875f"

bspc config external_rules_command $(which external_rules)

panel &
